// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNA5JTcOYKk0_Ut71To6J3UjrAAP-aASQ',
    appId: '1:8769981352:web:5f8682164bada3fa9eeb9d',
    messagingSenderId: '8769981352',
    projectId: 'e-commerce-591dc',
    authDomain: 'e-commerce-591dc.firebaseapp.com',
    storageBucket: 'e-commerce-591dc.firebasestorage.app',
    measurementId: 'G-8NMNKR0MZD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSyHJFtipG2wBB_O_n-0ItgTyqDhD1-F4',
    appId: '1:8769981352:android:d1424dd8841ff7bb9eeb9d',
    messagingSenderId: '8769981352',
    projectId: 'e-commerce-591dc',
    storageBucket: 'e-commerce-591dc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBu-ubCnRcRDBnGQ9oDyFvl9RvHFK_mFbI',
    appId: '1:8769981352:ios:0f28a65f8bae46019eeb9d',
    messagingSenderId: '8769981352',
    projectId: 'e-commerce-591dc',
    storageBucket: 'e-commerce-591dc.firebasestorage.app',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBu-ubCnRcRDBnGQ9oDyFvl9RvHFK_mFbI',
    appId: '1:8769981352:ios:0f28a65f8bae46019eeb9d',
    messagingSenderId: '8769981352',
    projectId: 'e-commerce-591dc',
    storageBucket: 'e-commerce-591dc.firebasestorage.app',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNA5JTcOYKk0_Ut71To6J3UjrAAP-aASQ',
    appId: '1:8769981352:web:57efbe63b8ba808c9eeb9d',
    messagingSenderId: '8769981352',
    projectId: 'e-commerce-591dc',
    authDomain: 'e-commerce-591dc.firebaseapp.com',
    storageBucket: 'e-commerce-591dc.firebasestorage.app',
    measurementId: 'G-FQREP6XQEW',
  );

}